#!/bin/sh           
#PBS -l mem=5g
#PBS -l ddisk=1gb
#PBS -l walltime=00:30:00
#PBS -l nodes=1:ppn=1
#PBS -j eo
#PBS -m ae
#PBS -o /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/logs
#PBS -e /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/logs
#PBS -M michelle01.klein@dkfz-heidelberg.de



python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/1_Get_Gene_Names.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/SV_gbm_somatic.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/rautry/TRAPD_output/burden.out_cases_snpfile_0.001_HGGONLY_CADD15.txt --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden2nd_Gene1_exon_somatic.csv --outfB=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene1_exon_somatic.csv --outfSV=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/SV_Gene1_exon_somatic.csv --input=Gene1_exon;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/1_Get_Gene_Names.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/SV_gbm_somatic.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/rautry/TRAPD_output/burden.out_cases_snpfile_0.001_HGGONLY_CADD15.txt --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden2nd_Gene2_exon_somatic.csv --outfB=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene2_exon_somatic.csv --outfSV=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/SV_Gene2_exon_somatic.csv --input=Gene2_exon;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/1_Get_Gene_Names.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/SV_gbm_somatic.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/rautry/TRAPD_output/burden.out_cases_snpfile_0.001_HGGONLY_CADD15.txt --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden2nd_Gene1_intron_somatic.csv --outfB=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene1_intron_somatic.csv --outfSV=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/SV_Gene1_intron_somatic.csv --input=Gene1_intron;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/1_Get_Gene_Names.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/SV_gbm_somatic.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/rautry/TRAPD_output/burden.out_cases_snpfile_0.001_HGGONLY_CADD15.txt --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden2nd_Gene2_intron_somatic.csv --outfB=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene2_intron_somatic.csv --outfSV=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/SV_Gene2_intron_somatic.csv --input=Gene2_intron;

python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/1_Get_Gene_Names2.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/SV_gbm_somatic.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/rautry/TRAPD_output/burden.out_cases_snpfile_0.001_HGGONLY_CADD15.txt --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden2nd_Gene1_exon_somatic2.csv --outfB=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene1_exon_somatic2.csv --outfSV=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/SV_Gene1_exon_somatic2.csv --input=Gene1_exon;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/1_Get_Gene_Names2.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/SV_gbm_somatic.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/rautry/TRAPD_output/burden.out_cases_snpfile_0.001_HGGONLY_CADD15.txt --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden2nd_Gene2_exon_somatic2.csv --outfB=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene2_exon_somatic2.csv --outfSV=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/SV_Gene2_exon_somatic2.csv --input=Gene2_exon;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/1_Get_Gene_Names2.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/SV_gbm_somatic.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/rautry/TRAPD_output/burden.out_cases_snpfile_0.001_HGGONLY_CADD15.txt --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden2nd_Gene1_intron_somatic2.csv --outfB=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene1_intron_somatic2.csv --outfSV=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/SV_Gene1_intron_somatic2.csv --input=Gene1_intron;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/1_Get_Gene_Names2.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/SV_gbm_somatic.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/rautry/TRAPD_output/burden.out_cases_snpfile_0.001_HGGONLY_CADD15.txt --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden2nd_Gene2_intron_somatic2.csv --outfB=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene2_intron_somatic2.csv --outfSV=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/SV_Gene2_intron_somatic2.csv --input=Gene2_intron;

python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/2_Get_results.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/SV_Gene1_exon_somatic.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden2nd_Gene1_exon_somatic.csv --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Burden2nd_Gene1_exon_somatic.csv --input=Gene1_exon;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/2_Get_results.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/SV_Gene2_exon_somatic.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden2nd_Gene2_exon_somatic.csv --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Burden2nd_Gene2_exon_somatic.csv --input=Gene2_exon;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/2_Get_results.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/SV_Gene1_intron_somatic.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden2nd_Gene1_intron_somatic.csv --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Burden2nd_Gene1_intron_somatic.csv --input=Gene1_intron;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/2_Get_results.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/SV_Gene2_intron_somatic.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden2nd_Gene2_intron_somatic.csv --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Burden2nd_Gene2_intron_somatic.csv --input=Gene2_intron;

python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/3_Update_burden_file.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Burden_results_genes_GBM.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene1_exon_somatic.csv --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Update_Burden_result_Gene1_exon_somatic.csv --input=Gene1_exon;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/3_Update_burden_file.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Burden_results_genes_GBM.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene2_exon_somatic.csv --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Update_Burden_result_Gene2_exon_somatic.csv --input=Gene2_exon;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/3_Update_burden_file.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Burden_results_genes_GBM.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene1_intron_somatic.csv --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Update_Burden_result_Gene1_intron_somatic.csv --input=Gene1_intron;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/3_Update_burden_file.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Burden_results_genes_GBM.csv --comp=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene2_intron_somatic.csv --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Update_Burden_result_Gene2_intron_somatic.csv --input=Gene2_intron;

python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/3_Update_burden_file2.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/rautry/TRAPD_output/burden.out_cases_snpfile_0.001_HGGONLY_CADD15.txt --comp=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene1_exon_somatic2.csv --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Update_Burden_result_Gene1_exon_somatic2.csv --input=Gene1_exon;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/3_Update_burden_file2.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/rautry/TRAPD_output/burden.out_cases_snpfile_0.001_HGGONLY_CADD15.txt --comp=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene2_exon_somatic2.csv --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Update_Burden_result_Gene2_exon_somatic2.csv --input=Gene2_exon;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/3_Update_burden_file2.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/rautry/TRAPD_output/burden.out_cases_snpfile_0.001_HGGONLY_CADD15.txt --comp=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene1_intron_somatic2.csv --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Update_Burden_result_Gene1_intron_somatic2.csv --input=Gene1_intron;
python /b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/3_Update_burden_file2.py --inf=/b06x-isilon/b06x-p/PanCanPredispo/rautry/TRAPD_output/burden.out_cases_snpfile_0.001_HGGONLY_CADD15.txt --comp=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Genes_Burden_Gene2_intron_somatic2.csv --outf=/b06x-isilon/b06x-p/PanCanPredispo/2ndHitAnalysis/mklein/SV/gbm_output/Update_Burden_result_Gene2_intron_somatic2.csv --input=Gene2_intron;
